### ISSUE TITLE
Can’t play video on macOS

### ISSUE THREAD

**Issue by likecreep** [MediaBrowser/emby-theater-electron#112]
Hi, I build this app to use on macOS. everything works fine but just can’t play videos. It will only show an endless loading circle. But if I set an external player, everything works fine. Is there a way to fix this? Thanks.

**Comment by henryl46** [comment]
me, too...

**Comment by LukePulverenti** [comment]
HI, are you not able to use our dedicated MacOS app?

**Comment by henryl46** [comment]
Emby theater didn't work very well on M1 Mac, the reason is that the app can not get the right path of the homebrew and mpv in /opt/homebrew in M1 mac.. The current version 3.0.15 can only detect the path in /usr/local/bin/brew as intel Mac

**Comment by LukePulverenti** [comment]
Have you tried the downloadable version of this?
https://emby.media/emby-theater-macos.html

**Comment by henryl46** [comment]
This one played well, but I think the performance didnt play as well as emby theater

**Comment by LukePulverenti** [comment]
> This one played well, but I think the performance didnt play as well as emby theater

Can you please describe that? Did you install from the store or use the newer downloadable build?

**Comment by henryl46** [comment]
My bad, I mean 'This one played well, but I think the performance didnt play as well as emby theater Electron'. I downloaded emby.app in the official website, but sometimes the function like FF and FB didnt play so well as they in the Emby theater electron.
