### ISSUE TITLE
mpv player cannot play

### ISSUE THREAD

**Issue by 1056824847** [MediaBrowser/emby-theater-electron#113]
May I ask whether your mpv uses https://github.com/Kagami/mpv.js/ this library, I use your mpv-arm64.node this file can not be played in my code, it shows that the plug-in cannot be loaded, please ask apt-get install libmpv1 libavformat-dev and gcc -Wl,--no-as-needed -shared -lavformat -o /path/to/libffmpeg.so these two commands are not, but I still can't run after I run

**Comment by LukePulverenti** [comment]
Hi, please try our new Emby Theater Linux packages:
https://emby.media/emby-theater-linux.html

Please feel free to re-open if you're still having an issue. Thanks.
