### ISSUE TITLE
Audio Language not set right between diffent series.

### ISSUE THREAD

**Issue by geosone** [MediaBrowser/emby-theater-electron#117]
When you play a playlist that has diffent series in the list (#arrowoserse) when switching between the diffent series the correct audio Langage is not set correctly.

**Comment by LukePulverenti** [comment]
Hi, please go over a specific example. Thanks.

**Comment by geosone** [comment]
for ex from this episode

`root@media:/mnt/mergefs/Serien/Arrow (2012)/Season 3# mediainfo 'Arrow - S03E15 - Nanda Parbat.mkv'
General
Unique ID                                : 48790682688310707638410629627144481063 (0x24B4BE61CA254112CAD87804594AA927)
Complete name                            : Arrow - S03E15 - Nanda Parbat.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 6.01 GiB
Duration                                 : 42 min 21 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 20.3 Mb/s
Encoded date                             : UTC 2019-03-27 20:20:53
Writing application                      : MakeMKV v1.14.3 linux(x64-release)
Writing library                          : libmakemkv v1.14.3 (1.3.5/1.4.7) x86_64-pc-linux-gnu

Video
ID                                       : 1
ID in the original source medium         : 4113 (0x1011)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 2 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 2 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 42 min 19 s
Bit rate mode                            : Variable
Bit rate                                 : 15.9 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.320
Stream size                              : 4.71 GiB (78%)
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #1
ID                                       : 2
ID in the original source medium         : 4352 (0x1100)
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 42 min 21 s
Bit rate mode                            : Variable
Bit rate                                 : 2 175 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 659 MiB (11%)
Title                                    : Surround 5.1
Language                                 : English
Default                                  : Yes
Forced                                   : No
Original source medium                   : Blu-ray

Audio #2
ID                                       : 3
ID in the original source medium         : 4352 (0x1100)
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 42 min 21 s
Bit rate mode                            : Constant
Bit rate                                 : 1 509 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 457 MiB (7%)
Title                                    : Surround 5.1
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #3
ID                                       : 4
ID in the original source medium         : 4353 (0x1101)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 42 min 21 s
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 194 MiB (3%)
Title                                    : Surround 5.1
Language                                 : German
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #1
ID                                       : 5
ID in the original source medium         : 4608 (0x1200)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 42 min 15 s
Bit rate                                 : 38.3 kb/s
Count of elements                        : 1194
Stream size                              : 11.6 MiB (0%)
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #2
ID                                       : 7
ID in the original source medium         : 4609 (0x1201)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 42 min 15 s
Bit rate                                 : 44.6 kb/s
Count of elements                        : 1198
Stream size                              : 13.5 MiB (0%)
Language                                 : German
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #3
ID                                       : 9
ID in the original source medium         : 4610 (0x1202)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 12 min 12 s
Bit rate                                 : 591 b/s
Count of elements                        : 6
Stream size                              : 52.9 KiB (0%)
Language                                 : German
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Menu
00:00:00.000                             : en:Chapter 01
00:00:27.569                             : en:Chapter 02
00:01:43.812                             : en:Chapter 03
00:09:53.926                             : en:Chapter 04
00:14:17.398                             : en:Chapter 05
00:18:24.937                             : en:Chapter 06
00:27:15.467                             : en:Chapter 07
00:33:23.001                             : en:Chapter 08
00:41:51.175                             : en:Chapter 09

`
to

`root@media:/mnt/mergefs/Serien/The Flash (2014)/Season 1# mediainfo The\ Flash\ -\ S01E15\ -\ Im\ Wettlauf\ mit\ der\ Zeit.mkv 
General
Unique ID                                : 196144152329511103390015161205295748629 (0x938FFD58F7AB5D5AB5873AE74BBD1615)
Complete name                            : The Flash - S01E15 - Im Wettlauf mit der Zeit.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 5.12 GiB
Duration                                 : 42 min 6 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 17.4 Mb/s
Movie name                               : The Flash Season 1 Disc 3
Writing application                      : Lavf58.45.100
Writing library                          : Lavf58.45.100
ErrorDetectionType                       : Per level 1

Video
ID                                       : 1
ID in the original source medium         : 4113 (0x1011)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main@L4@High
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 42 min 5 s
Bit rate                                 : 16.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (23976/1000) FPS
Original frame rate                      : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Bits/(Pixel*Frame)                       : 0.321
Stream size                              : 4.69 GiB (92%)
Writing library                          : Lavc58.91.100 hevc_nvenc
Language                                 : English
Default                                  : Yes
Forced                                   : No
Original source medium                   : Blu-ray

Audio #1
ID                                       : 2
ID in the original source medium         : 4352 (0x1100)
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 42 min 6 s
Bit rate mode                            : Variable
Bit rate                                 : 2 298 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossless
Delay relative to video                  : 21 ms
Stream size                              : 692 MiB (13%)
Title                                    : Surround 5.1
Language                                 : English
Default                                  : Yes
Forced                                   : No
Original source medium                   : Blu-ray

Audio #2
ID                                       : 3
ID in the original source medium         : 4352 (0x1100)
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Codec ID                                 : A_DTS
Duration                                 : 42 min 6 s
Bit rate mode                            : Constant
Bit rate                                 : 1 509 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Delay relative to video                  : 21 ms
Stream size                              : 454 MiB (9%)
Title                                    : Surround 5.1
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #3
ID                                       : 4
ID in the original source medium         : 4353 (0x1101)
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 42 min 6 s
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 57.8 MiB (1%)
Title                                    : Stereo
Writing library                          : Lavc58.91.100 aac
Language                                 : French
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Audio #4
ID                                       : 5
ID in the original source medium         : 4354 (0x1102)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 42 min 6 s
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Delay relative to video                  : 21 ms
Stream size                              : 193 MiB (4%)
Title                                    : Surround 5.1
Language                                 : German
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #1
ID                                       : 6
ID in the original source medium         : 4608 (0x1200)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 42 min 3 s
Bit rate                                 : 42.5 kb/s
Count of elements                        : 1248
Stream size                              : 12.8 MiB (0%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
Original source medium                   : Blu-ray

Text #2
ID                                       : 7
ID in the original source medium         : 4609 (0x1201)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 42 min 3 s
Bit rate                                 : 34.6 kb/s
Count of elements                        : 1210
Stream size                              : 10.4 MiB (0%)
Language                                 : French
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #3
ID                                       : 8
ID in the original source medium         : 4610 (0x1202)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 42 min 3 s
Bit rate                                 : 49.7 kb/s
Count of elements                        : 1286
Stream size                              : 14.9 MiB (0%)
Language                                 : German
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #4
ID                                       : 9
ID in the original source medium         : 4611 (0x1203)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 42 min 1 s
Bit rate                                 : 36.8 kb/s
Count of elements                        : 1160
Stream size                              : 11.1 MiB (0%)
Language                                 : Dutch
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #5
ID                                       : 10
ID in the original source medium         : 4612 (0x1204)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 42 min 3 s
Bit rate                                 : 457 b/s
Count of elements                        : 16
Stream size                              : 137 KiB (0%)
Language                                 : German
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Menu
00:00:00.000                             : :Chapter 01
00:01:16.868                             : :Chapter 02
00:02:38.199                             : :Chapter 03
00:08:27.548                             : :Chapter 04
00:14:19.483                             : :Chapter 05
00:20:22.387                             : :Chapter 06
00:25:24.523                             : :Chapter 07
00:30:06.638                             : :Chapter 08
00:41:36.160                             : :Chapter 09
`

the selected german audio wont stay 
in the player under audio it says its german but the audio langiage is english 
by selecting another audio language an swithing it back to german restores the german audio playback.

**Comment by LukePulverenti** [comment]
Hi, can you try downloading the latest build and let us know how that compares? Thanks !

**Comment by geosone** [comment]
will look into it next week

**Comment by geosone** [comment]
funny at the moment its working

**Comment by LukePulverenti** [comment]
https://emby.media/community/index.php?/blogs/entry/611-%C2%A0emby-linux-the-public-beta-is-open-now/
