### ISSUE TITLE
player is separate from ui

### ISSUE THREAD

**Issue by gibbly** [MediaBrowser/emby-theater-electron#52]
I'm using i3wm on arch linux with the latest git and when i play a file the video plays as a separate window with the ui just showing black where the video should be.

**Comment by crazyjunk** [comment]
I‘m using rpi3 with latest image 3.0.8 and 3.0.6. i got the same issue + when the videofile have a cover, it shows it up in the foreground

**Comment by Titan3k** [comment]
I was using an rpi4 with i think 3.0.8 and same issue. Im currently re-flashing with 3.0.12.

**Comment by LukePulverenti** [comment]
Going forward we have an arch linux package built by us:
https://archlinux.org/packages/community/x86_64/emby-theater/
Please try that. Thanks !
