### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by MelvinLoos** [MediaBrowser/emby-theater-electron#9]
Ok so I have been looking at Electron for a while now but haven't had the time to actually play around with it yet. The apps that were made with it that I tried are awesome though so I am really curious how the emby app is. Anyway how would I run the app from this repo? 
I don't see any releases yet so I guess I still have to build it. I am a dev myself so pointing me in the right direction should get me going. Oh and I would be happy to help out with testing and stuff!

**Comment by G-Ray** [comment]
Hi @MelvinLoos 
```
npm install
npm start
```
