### ISSUE TITLE
Playback broken on Fedora 32

### ISSUE THREAD

**Issue by romainrbr** [MediaBrowser/emby-theater-electron#91]
Hello,

The playback of any file is currently broken on the latest Fedora.
To reproduce : 

```
git clone https://github.com/MediaBrowser/emby-theater-electron.git
cd emby-theater-electron
npm install
npm start
```

The app itself works fine, but trying to play any file ends up with a spinning circle on top of the media's art.
Nothing is logged, appart from the app trying to access the file locally (I've tried creating the file locally, but it doesn't play either) : 

```
emby-theater-electron on  HEAD [!] is 📦 v3.0.12 via ⬢ v12.16.3 via 🐍 v3.8.0 (romain) took 5s 
❯ npm start

> emby-theater@3.0.12 start /tmp/emby-fix-fedo/emby-theater-electron
> electron main.js

(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
Initializing cec-client...

{
  cecExePath: 'cec-client',
  cecEmitter: EventEmitter {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined
  }
}
UDP Client listening on 0.0.0.0:47149
starting udp receive timer with timeout ms: 1000
cec-client exited with code 1
timer expired 0 servers received
[]
fs access result for path: Error: ENOENT: no such file or directory, access '/data/tvshow/Malcolm in the Middle/Malcolm in the Middle - 3x20 - Jury Duty.avi'
```

Playing a file still works in branch `3.0.11`, but the GUI on top of MPV is having issues (turning black when moving the mouse, etc ..)
I've also noticed that doing the following : 
```
git checkout 3.0.11
npm install
git checkout 3.0.12
npm install
```

Doesn't fix the issue, but instead of a spinning wheel on top of the media art, we get an empty player GUI : 
![image](https://user-images.githubusercontent.com/10381609/97114511-b7a4bc00-16cf-11eb-942b-f98a08b85594.png)

The same issues happens when building an AppImage (https://github.com/MediaBrowser/emby-theater-electron/pull/90) , and running it on any platform.

**Comment by romainrbr** [comment]
Some additional information : 

I managed to have the app working (and playing video) by grabbing `libmpv.so` from a debian system, and replacing my `/usr/lib64/libmpv.so.1.107.0`.

After that, a `npm start` at least works.

**Comment by finfa** [comment]
I have exactly the same issue and output with Ubuntu 18.04. No matter if I install the deb or checkout or substitute the libmpv in the directory of the program. I also installed libmpv-dev.

3.0.11 works, but as soon as you mouse over, the screen turns black permanently.

**Comment by LukePulverenti** [comment]
Hi, can you please try downloading the .deb again and see how that compares? Thanks.

**Comment by likecreep** [comment]
same problem on macOS

**Comment by LukePulverenti** [comment]
Hi, please try our new Emby Theater Linux packages:
https://emby.media/emby-theater-linux.html

Please feel free to re-open if you're still having an issue. Thanks.

**Comment by LukePulverenti** [comment]
https://emby.media/community/index.php?/blogs/entry/611-%C2%A0emby-linux-the-public-beta-is-open-now/
