### ISSUE TITLE
emby-theater-rpi_3.0.12.zip launches to Debian login screen

### ISSUE THREAD

**Issue by scottbouch** [MediaBrowser/emby-theater-electron#92]
Just tried the RPI image on a Pi 3, and it just boots to the Debian 10 login screen, does not launch the electron emby theatre. 

I am now stuck, as I don't know the credentials for the Debian user to log in and try to manually launch ET, or set the config up.

Thanks, Scott.

**Comment by LukePulverenti** [comment]
Hi, please try our new Emby Theater Linux packages:
https://emby.media/emby-theater-linux.html

Please feel free to re-open if you're still having an issue. Thanks.

**Comment by LukePulverenti** [comment]
https://emby.media/community/index.php?/blogs/entry/611-%C2%A0emby-linux-the-public-beta-is-open-now/
